revamping to allow local vhost setup and easy update by git pull

diff --git a/rootfs/bootstrap b/rootfs/bootstrap
--- a/rootfs/bootstrap
+++ b/rootfs/bootstrap
@@ -2,6 +2,8 @@
 
 set -e
 
+rsync -av --ignore-existing /etc/nginx/assets/ /etc/nginx
+
 rm -fr \
   /etc/nginx-vhosts \
 ;
@@ -29,20 +31,21 @@ EOF
 ERROR_PREFIX="\e[31mERROR\e[0m"
 WARNING_PREFIX="\e[91mWARNING\e[0m"
 
-nginx_user_array=(`grep -o "^user\s\+[^;]\+" /etc/nginx/nginx.conf`)
+nginx_user_array=(`grep -q -o "^user\s\+[^;]\+" /etc/nginx/**/*.conf`)
 [[ -n ${nginx_user_array[1]} ]] && nginx_user="${nginx_user_array[1]}" || nginx_user="nginx"
 
 for d in $(find /etc/vhosts -type d -maxdepth 1 -mindepth 1); do
 
   unset \
     hostname \
+    conf_dir \
     vhost_conf \
-    cert_file_array \
-    cert_file \
+    ssl_directives \
   ;
 
   hostname="${d##*/}"
-  vhost_conf="$d/vhost.conf"
+  conf_dir="$d/deploy/dev/nginx"
+  vhost_conf="$conf_dir/vhost.conf"
 
   echo
   echo -e "[ \e[1;35m$hostname\e[0m ]"
@@ -54,29 +57,38 @@ for d in $(find /etc/vhosts -type d -maxdepth 1 -mindepth 1); do
 
   echo "address=/$hostname/$listen_address" >> /etc/dnsmasq.conf
 
-  if [[ $nginx_user != root ]]; then
-    for k in \
-      ssl_certificate \
-      ssl_certificate_key \
-    ; do
+  if [[ -f "$conf_dir/local/certificate.crt" ]]; then
 
-      cert_file_array=(`grep -o "^$k\s\+[^;]\+" $vhost_conf`) || true
-      cert_file="${cert_file_array[1]//\$host/$hostname}"
+    ssl_directives="
+      ssl_certificate     $conf_dir/local/certificate.crt;
+      ssl_certificate_key $conf_dir/local/certificate.key;
+      listen              $listen_address:443 ssl;
+    "
 
-      if [[ -n $cert_file ]]; then
-        su $nginx_user -s /bin/sh -c "cat $cert_file > /dev/null" || {
-          echo -e "$ERROR_PREFIX: make sure $k file exists and can be read by unprivileged users"
-          echo -e "$ERROR_PREFIX: $cert_file not readable by $nginx_user user"
+    if [[ $nginx_user != root ]]; then
+
+      for f in \
+        "$conf_dir/local/certificate.crt" \
+        "$conf_dir/local/certificate.key"  \
+      ; do
+
+        su $nginx_user -s /bin/sh -c "cat $f > /dev/null" || {
+          echo -e "$WARNING_PREFIX: make sure $f file exists and is readable by unprivileged users"
+          echo -e "$ERROR_PREFIX: $f not readable by $nginx_user user"
         }
-      fi
 
-    done
+      done
+
+    fi
+
   fi
 
   for e in \
     "server" \
     "listen" \
     "server_name" \
+    "ssl_certificate" \
+    "ssl_certificate_key" \
   ; do
     if grep -q "^[^#]\?$e\s\+" $vhost_conf; then
       echo -e "$WARNING_PREFIX: $e directive detected in $vhost_conf"
@@ -85,10 +97,11 @@ for d in $(find /etc/vhosts -type d -maxdepth 1 -mindepth 1); do
 
   cat <<EOF > /etc/nginx-vhosts/$hostname.conf
 server {
+  $ssl_directives
   listen $listen_address:80;
-  listen $listen_address:443 ssl;
   server_name $hostname;
   include $vhost_conf;
+  include $conf_dir/local/*.conf;
 }
 EOF
 
